### 应用分页查询
GET http://localhost:18080/common-support/app/page?appId=1&size=20&current=1

### 应用分页查询，这里的展示是另外一种方式，验证全局异常处理
POST http://localhost:18080/common-support/app/page-another
Content-Type: application/json

{
  "entity": {
    "appCode": "test"
  },
  "size": -1,
  "current": 1
}


### 新增应用
POST http://localhost:18080/common-support/app/add
Content-Type: application/json

{
  "appCode": "test",
  "createUserId": 0,
  "appKey": "test",
  "secretKey": "test",
  "appName": "test",
  "appLogo": "test",
  "appUsername": "test",
  "appPhone": "test",
  "appEvidence": "test"
}

### 修改应用
POST http://localhost:8080/common-support/app/update
Content-Type: application/json

{
  "appId": 9,
  "appCode": "test02",
  "createUserId": 0,
  "appKey": "test",
  "secretKey": "test",
  "appName": "test",
  "appLogo": "test",
  "appUsername": "test",
  "appPhone": "test",
  "appEvidence": "test"
}

### 删除应用
POST http://localhost:8080/common-support/app/delete?appId=9
Content-Type: application/json

