CREATE SCHEMA "CSP_MANAGER";


CREATE TABLE "CSP_MANAGER"."GXYYZC_YYB"
(
    "YY_ID" BIGINT NOT NULL,
    "YY_MC" VARCHAR(255),
    "YY_JC" VARCHAR(1024),
    "YY_NLBD" VARCHAR(255),
    "YY_FWXY" TINYINT,
    "YY_SMRZ" TINYINT,
    "YY_KEY" VARCHAR(1024),
    "YY_SECRET" VARCHAR(1024),
    "YY_ZT" TINYINT,
    "YY_ISDELETE" TINYINT,
    "YY_CREATETIME" TIMESTAMP(6),
    "YY_UPDATETIME" TIMESTAMP(6),
    "YY_BZ" VARCHAR(1024),
    "YY_CREATENAME" VARCHAR(255),
    "YY_UPDATENAME" VARCHAR(255),
    "YY_CODE" VARCHAR(255),
    "YY_SHZT" TINYINT,
    "YY_TB" VARCHAR(255),
    "YH_XH_ID" VARCHAR(255),
    "YY_WGKEY" VARCHAR(1024),
    "YY_WGSECRET" VARCHAR(1024)) ;

COMMENT ON TABLE "CSP_MANAGER"."GXYYZC_YYB" IS '应用列表';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YH_XH_ID" IS '用户id';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_BZ" IS '备注';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_CODE" IS 'appid';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_CREATENAME" IS '创建人';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_CREATETIME" IS '创建时间';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_FWXY" IS '同意服务协议 0否 1是';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_ID" IS 'id';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_ISDELETE" IS '是否删除 0正常 1删除';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_JC" IS '应用简介';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_KEY" IS '密钥';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_MC" IS '应用名称';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_NLBD" IS '能力绑定';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_SECRET" IS '密令';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_SHZT" IS '审核状态 0正常 1删除 2锁定 3待审核 4未通过';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_SMRZ" IS '是否实名（认证） 0否 1是';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_TB" IS '应用图标路径';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_UPDATENAME" IS '修改人';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_UPDATETIME" IS '修改时间';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_ZT" IS '状态（认证） 0不启用 1启用';



CREATE TABLE "CSP_MANAGER"."GXYYZC_NLSQ"
(
    "NLSQ_ID" BIGINT AUTO_INCREMENT NOT NULL,
    "NL_ID" BIGINT NOT NULL,
    "YY_ID" BIGINT NOT NULL,
    "YH_ID" BIGINT,
    "NL_MC" VARCHAR(50) NOT NULL,
    "NL_LX" VARCHAR(50),
    "YY_MC" VARCHAR(50) NOT NULL,
    "DYLXZ" INT,
    "BFSXZ" INT,
    "NLSQ_SQJKLB" VARCHAR(255),
    "QY_MC" VARCHAR(50),
    "ZF_BMMC" VARCHAR(50),
    "ZT" TINYINT DEFAULT 0,
    "NLSQ_SQSM" TEXT,
    "BZ" TEXT,
    "NLSQ_SPSJ" TIMESTAMP(6),
    "IS_DELETE" TINYINT DEFAULT 0,
    "NLSQ_CJSJ" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "NLSQ_GXSJ" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "NLSQ_SFTYXY" TINYINT DEFAULT 0 NOT NULL,
    "WG_QQMWGZ" VARCHAR(20) DEFAULT 'none' NOT NULL,
    "WG_XYMWGZ" VARCHAR(20) DEFAULT 'none' NOT NULL,
    NOT CLUSTER PRIMARY KEY("NLSQ_ID")) STORAGE(ON "CSP_MANAGER", CLUSTERBTR) AUTO_INCREMENT = 1749635062376300546;

COMMENT ON TABLE "CSP_MANAGER"."GXYYZC_NLSQ" IS '应用申请表';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."BFSXZ" IS '并发数限制';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."BZ" IS '备注(驳回、停用的原因)';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."DYLXZ" IS '调用量限制';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."IS_DELETE" IS '逻辑删除';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."NLSQ_CJSJ" IS '创建时间（提交时间）';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."NLSQ_GXSJ" IS '更新时间';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."NLSQ_ID" IS '能力申请表ID';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."NLSQ_SFTYXY" IS '是否同意所有服务所需协议(默认0同意 1不同意)';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."NLSQ_SPSJ" IS '审批时间';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."NLSQ_SQJKLB" IS '申请接口id列表（id之间用逗号隔开）';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."NLSQ_SQSM" IS '申请说明';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."NL_ID" IS '能力ID';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."NL_LX" IS '能力类型';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."NL_MC" IS '能力名称';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."QY_MC" IS '企业名称';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."WG_QQMWGZ" IS '请求密文规则(默认:none不做处理 crypt加密文 sign加签名 sign_crypt加密加签)';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."WG_XYMWGZ" IS '响应密文规则(默认:none不做处理 crypt加密文 sign加签名 sign_crypt加密加签)';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."YH_ID" IS '用户账户ID';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."YY_ID" IS '应用ID';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."YY_MC" IS '应用名称';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."ZF_BMMC" IS '政府部门名称';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."ZT" IS '状态(默认:0待审核 1审核通过 2审核不通过 3已停用)';


CREATE TABLE "CSP_MANAGER"."GXYYZC_NL"
(
    "NL_ID" BIGINT AUTO_INCREMENT NOT NULL,
    "NL_LX" INT NOT NULL,
    "NL_MC" VARCHAR(50) NOT NULL,
    "YH_ID" BIGINT,
    "NL_TGZ" VARCHAR(255),
    "NL_MS" VARCHAR(255),
    "ZT" TINYINT DEFAULT 0,
    "BZ" VARCHAR(255),
    "CJSJ" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "GXSJ" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "IS_DELETE" TINYINT DEFAULT 0 NOT NULL,
    NOT CLUSTER PRIMARY KEY("NL_ID")) STORAGE(ON "CSP_MANAGER", CLUSTERBTR) AUTO_INCREMENT = 1749713381597691906;

COMMENT ON TABLE "CSP_MANAGER"."GXYYZC_NL" IS '能力表';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NL"."BZ" IS '备注(审核操作原因备注)';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NL"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NL"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NL"."NL_ID" IS '能力ID';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NL"."NL_LX" IS '能力类型';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NL"."NL_MC" IS '能力名称';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NL"."NL_MS" IS '能力描述';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NL"."NL_TGZ" IS '能力提供者';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NL"."YH_ID" IS '注册人账号ID';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NL"."ZT" IS '状态 (默认:0未提交1待审核 2审核未通过 3未发布 4已发布 5已下线)';



CREATE TABLE "CSP_MANAGER"."GXYYZC_NLJK"
(
    "NLJK_ID" BIGINT AUTO_INCREMENT NOT NULL,
    "NL_ID" BIGINT NOT NULL,
    "NLJK_MC" VARCHAR(512) NOT NULL,
    "NLJK_MS" VARCHAR(2048),
    "DYLXZ" INT,
    "BFSXZ" INT,
    "NLJK_XYGS" TEXT,
    "NLJK_XY" VARCHAR(20),
    "NLJK_ZJDZ" VARCHAR(255),
    "NLJK_URL" VARCHAR(255) NOT NULL,
    "NLJK_BBH" VARCHAR(50),
    "IS_DELETE" TINYINT DEFAULT 0,
    "NLJK_CJSJ" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "NLJK_GXSJ" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "WG_GY" VARCHAR(255),
    "WG_SY" VARCHAR(255),
    "NLJK_QQFF" VARCHAR(50),
    "NLJK_QQSL" TEXT,
    "NLJK_XYSL" TEXT,
    "NLJK_XYZTM" TEXT,
    NOT CLUSTER PRIMARY KEY("NLJK_ID"),
    CONSTRAINT "MANAGE_ABILITY_API_MANAGE_ABILITY_FK" FOREIGN KEY("NL_ID") REFERENCES "CSP_MANAGER"."GXYYZC_NL"("NL_ID"),
    CONSTRAINT "GXYYZC_NLJK_URL_UN" UNIQUE("NLJK_URL")) STORAGE(ON "CSP_MANAGER", CLUSTERBTR) AUTO_INCREMENT = 1749715486085529603;

COMMENT ON TABLE "CSP_MANAGER"."GXYYZC_NLJK" IS '能力接口表';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."BFSXZ" IS '并发数限制';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."DYLXZ" IS '调用量限制';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."IS_DELETE" IS '逻辑删除';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."NLJK_BBH" IS '版本号';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."NLJK_CJSJ" IS '创建时间';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."NLJK_GXSJ" IS '更新时间';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."NLJK_ID" IS 'ApiID';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."NLJK_MC" IS 'api名称';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."NLJK_MS" IS 'api描述';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."NLJK_QQFF" IS '请求方式';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."NLJK_QQSL" IS '请求示例';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."NLJK_URL" IS 'URL路径';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."NLJK_XY" IS '协议http/https';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."NLJK_XYGS" IS '响应格式';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."NLJK_XYSL" IS '响应示例';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."NLJK_XYZTM" IS '响应状态码';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."NLJK_ZJDZ" IS '主机地址';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."NL_ID" IS '能力ID';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."WG_GY" IS '公钥';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."WG_SY" IS '私钥';


INSERT INTO CSP_MANAGER.GXYYZC_YYB
(YY_ID, YY_MC, YY_JC, YY_NLBD, YY_FWXY, YY_SMRZ, YY_KEY, YY_SECRET, YY_ZT, YY_ISDELETE, YY_CREATETIME, YY_UPDATETIME, YY_BZ, YY_CREATENAME, YY_UPDATENAME, YY_CODE, YY_SHZT, YY_TB, YH_XH_ID, YY_WGKEY, YY_WGSECRET)
VALUES(1749358566426378242, '金融库环境', '金融库环境', NULL, NULL, NULL, 'MFkwEwYHKoZIzj0CAQYIKoEcz1UBgi0DQgAEhSEgLyS7QE6txeo71YFUf3NVW+OgdBfDmvuctHMRQ+wK6xWClshpzboCPEj6m+42qpsoD62JwbQ8V8EecPXGzQ==', 'MIGTAgEAMBMGByqGSM49AgEGCCqBHM9VAYItBHkwdwIBAQQgepYrvuBpzQXdhlARCWkQGPJSHGcdq3Qg+pHabscs9GCgCgYIKoEcz1UBgi2hRANCAASFISAvJLtATq3F6jvVgVR/c1Vb46B0F8Oa+5y0cxFD7ArrFYKWyGnNugI8SPqb7jaqmygPrYnBtDxXwR5w9cbN', 0, 0, '2024-01-22 17:09:18.125', '2024-01-22 17:09:18.125', NULL, NULL, NULL, '68294703', NULL, 'https://fuss10.elemecdn.com/e/5d/4a731a90594a4af544c0c25941171jpeg.jpeg', '56415082531', 'MFkwEwYHKoZIzj0CAQYIKoEcz1UBgi0DQgAEdDinMgZB9Hs5gioL2LZdGqtJXZPKobnh/CvpOLvz8E+bulpuNsSo2BnsGFql7mpzoEkXPskntIrygfRmZZrBxw==', 'MIGTAgEAMBMGByqGSM49AgEGCCqBHM9VAYItBHkwdwIBAQQgLBLhV4/AxbmoTvirE0RxNh2+FasBJ//lecM3lm+XO4OgCgYIKoEcz1UBgi2hRANCAAR0OKcyBkH0ezmCKgvYtl0aq0ldk8qhueH8K+k4u/PwT5u6Wm42xKjYGewYWqXuanOgSRc+ySe0ivKB9GZlmsHH');

INSERT INTO CSP_MANAGER.GXYYZC_NLSQ
(NLSQ_ID, NL_ID, YY_ID, YH_ID, NL_MC, NL_LX, YY_MC, DYLXZ, BFSXZ, NLSQ_SQJKLB, QY_MC, ZF_BMMC, ZT, NLSQ_SQSM, BZ, NLSQ_SPSJ, IS_DELETE, NLSQ_CJSJ, NLSQ_GXSJ, NLSQ_SFTYXY, WG_QQMWGZ, WG_XYMWGZ)
VALUES(1749635062376300545, 1749634078933647361, 1749358566426378242, 56415082531, '金融库环境', '1', '金融库环境', NULL, NULL, '1749634675208486914', NULL, '融信服', 1, '金融库环境', NULL, NULL, 0, '2024-01-23 11:18:51.379', '2024-01-23 11:28:26.271', 0, 'sign_crypt', 'sign_crypt');

INSERT INTO CSP_MANAGER.GXYYZC_NL
(NL_ID, NL_LX, NL_MC, YH_ID, NL_TGZ, NL_MS, ZT, BZ, CJSJ, GXSJ, IS_DELETE)
VALUES(1749634078933647361, 3, '金融库环境', NULL, NULL, NULL, 4, '审核通过', '2024-01-23 11:14:56.909', '2024-01-23 11:24:45.860', 0);