CREATE SCHEMA "CSP_MANAGER" AUTHORIZATION "CSP_MANAGER";

CREATE TABLE "CSP_MANAGER"."GXYYZC_YYB"
(
"YY_ID" BIGINT NOT NULL,
"YY_MC" VARCHAR(255),
"YY_JC" VARCHAR(1024),
"YY_NLBD" VARCHAR(255),
"YY_FWXY" TINYINT,
"YY_SMRZ" TINYINT,
"YY_KEY" VARCHAR(1024),
"YY_SECRET" VARCHAR(1024),
"YY_ZT" TINYINT,
"YY_ISDELETE" TINYINT,
"YY_CREATETIME" TIMESTAMP(6),
"YY_UPDATETIME" TIMESTAMP(6),
"YY_BZ" VARCHAR(1024),
"YY_CREATENAME" VARCHAR(255),
"YY_UPDATENAME" VARCHAR(255),
"YY_CODE" VARCHAR(255),
"YY_SHZT" TINYINT,
"YY_TB" VARCHAR(255),
"YH_XH_ID" VARCHAR(255),
"YY_WGKEY" VARCHAR(1024),
"YY_WGSECRET" VARCHAR(1024),
CONSTRAINT "CSP_APPLICATION_PK" NOT CLUSTER PRIMARY KEY("YY_ID")) STORAGE(ON "CSP_MANAGER", CLUSTERBTR) ;

COMMENT ON TABLE "CSP_MANAGER"."GXYYZC_YYB" IS '应用列表';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YH_XH_ID" IS '用户id';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_BZ" IS '备注';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_CODE" IS 'appid';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_CREATENAME" IS '创建人';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_CREATETIME" IS '创建时间';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_FWXY" IS '同意服务协议 0否 1是';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_ID" IS 'id';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_ISDELETE" IS '是否删除 0正常 1删除';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_JC" IS '应用简介';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_KEY" IS '密钥';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_MC" IS '应用名称';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_NLBD" IS '能力绑定';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_SECRET" IS '密令';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_SHZT" IS '审核状态 0正常 1删除 2锁定 3待审核 4未通过';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_SMRZ" IS '是否实名（认证） 0否 1是';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_TB" IS '应用图标路径';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_UPDATENAME" IS '修改人';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_UPDATETIME" IS '修改时间';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YYB"."YY_ZT" IS '状态（认证） 0不启用 1启用';


