CREATE SCHEMA "CSP_MANAGER" AUTHORIZATION "CSP_MANAGER";
CREATE TABLE "CSP_MANAGER"."GXYYZC_YHB"
(
"YH_XH" VARCHAR(50) NOT NULL,
"YH_MC" VARCHAR(20),
"DHHM" VARCHAR(20),
"DZYX" VARCHAR(20),
"ZT" TINYINT DEFAULT 0 NOT NULL,
"QY_MC" VARCHAR(100),
"QY_ZCH" VARCHAR(255),
"QY_FDDBR" VARCHAR(20),
"QY_TP" VARCHAR(100),
"SQH" VARCHAR(100),
"QY_LXRXM" VARCHAR(50),
"QY_SFZH" VARCHAR(255),
"QY_DHHM" VARCHAR(50),
"ZF_MC" VARCHAR(50),
"ZF_ZCH" VARCHAR(255),
"ZF_FDDBR" VARCHAR(20),
"ZF_TP" VARCHAR(255),
"ZF_LXRXM" VARCHAR(50),
"ZF_SFZH" VARCHAR(255),
"ZF_DHHM" VARCHAR(50),
"SFKY" TINYINT DEFAULT 0,
"CJSJ" TIMESTAMP(6),
"BZ" VARCHAR(255),
"YH_LX" TINYINT DEFAULT 0,
CONSTRAINT "MANAGE_USER_PK" NOT CLUSTER PRIMARY KEY("YH_XH")) STORAGE(ON "CSP_MANAGER", CLUSTERBTR) ;

COMMENT ON TABLE "CSP_MANAGER"."GXYYZC_YHB" IS '用户表（共性实名认证使用）';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YHB"."BZ" IS '备注';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YHB"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YHB"."DHHM" IS '用户手机号';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YHB"."DZYX" IS '邮箱';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YHB"."QY_DHHM" IS '企业联系人手机号码';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YHB"."QY_FDDBR" IS '企业法定代表人';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YHB"."QY_LXRXM" IS '企业联系人姓名';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YHB"."QY_MC" IS '企业名称';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YHB"."QY_SFZH" IS '企业联系人身份证号';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YHB"."QY_TP" IS '营业执照扫描件';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YHB"."QY_ZCH" IS '营业执照注册号';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YHB"."SFKY" IS '账户是否可用（0可用  1已注销）';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YHB"."SQH" IS '授权函';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YHB"."YH_LX" IS '用户类型（0未实名游客 1企业用户 2政府用户）';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YHB"."YH_MC" IS '用户名称';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YHB"."YH_XH" IS '用户ID';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YHB"."ZF_DHHM" IS '政府部门联系人手机号码';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YHB"."ZF_FDDBR" IS '政府部门法定代表人';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YHB"."ZF_LXRXM" IS '政府部门联系人姓名';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YHB"."ZF_MC" IS '政府部门名称';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YHB"."ZF_SFZH" IS '政府部门联系人身份证号';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YHB"."ZF_TP" IS '政府部门营业执照扫描件';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YHB"."ZF_ZCH" IS '营业执照注册号';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_YHB"."ZT" IS '认证状态（0未实名 1待审核 2审核通过 3审核不通过）';


