CREATE SCHEMA "CSP_MANAGER" AUTHORIZATION "CSP_MANAGER";

CREATE TABLE "CSP_MANAGER"."GXYYZC_NLJK_QQCS"
(
"QQCS_ID" BIGINT AUTO_INCREMENT NOT NULL,
"NLJK_ID" BIGINT NOT NULL,
"QQCS_MC" VARCHAR(100) NOT NULL,
"QQCS_LX" VARCHAR(20) NOT NULL,
"QQCS_MS" VARCHAR(256),
"QQCS_SFBY" INT DEFAULT 0 NOT NULL,
CONSTRAINT "GXYYZC_MLJK_QQCS_PK" NOT CLUSTER PRIMARY KEY("QQCS_ID")) STORAGE(ON "CSP_MANAGER", CLUSTERBTR) AUTO_INCREMENT = 1749715486102306819;

COMMENT ON TABLE "CSP_MANAGER"."GXYYZC_NLJK_QQCS" IS '接口请求参数';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK_QQCS"."NLJK_ID" IS '能力接口ID';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK_QQCS"."QQCS_ID" IS '请求参数ID';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK_QQCS"."QQCS_LX" IS '请求参数类型';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK_QQCS"."QQCS_MC" IS '请求参数名称';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK_QQCS"."QQCS_MS" IS '描述';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK_QQCS"."QQCS_SFBY" IS '参数是否必要(默认0否 1是)';


