CREATE SCHEMA "CSP_MANAGER" AUTHORIZATION "CSP_MANAGER";

CREATE TABLE "CSP_MANAGER"."GXYYZC_NL"
(
"NL_ID" BIGINT AUTO_INCREMENT NOT NULL,
"NL_LX" INT NOT NULL,
"NL_MC" VARCHAR(50) NOT NULL,
"YH_ID" BIGINT,
"NL_TGZ" VARCHAR(255),
"NL_MS" VARCHAR(255),
"ZT" TINYINT DEFAULT 0,
"BZ" VARCHAR(255),
"CJSJ" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
"GXSJ" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
"IS_DELETE" TINYINT DEFAULT 0 NOT NULL,
NOT CLUSTER PRIMARY KEY("NL_ID")) STORAGE(ON "CSP_MANAGER", CLUSTERBTR) AUTO_INCREMENT = 1749713381597691906;

COMMENT ON TABLE "CSP_MANAGER"."GXYYZC_NL" IS '能力表';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NL"."BZ" IS '备注(审核操作原因备注)';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NL"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NL"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NL"."NL_ID" IS '能力ID';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NL"."NL_LX" IS '能力类型';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NL"."NL_MC" IS '能力名称';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NL"."NL_MS" IS '能力描述';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NL"."NL_TGZ" IS '能力提供者';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NL"."YH_ID" IS '注册人账号ID';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NL"."ZT" IS '状态 (默认:0未提交1待审核 2审核未通过 3未发布 4已发布 5已下线)';


