CREATE SCHEMA "CSP_MANAGER" AUTHORIZATION "CSP_MANAGER";

CREATE TABLE "CSP_MANAGER"."GXYYZC_NLJK_XYCS"
(
"XYCS_ID" BIGINT AUTO_INCREMENT NOT NULL,
"NLJK_ID" BIGINT NOT NULL,
"XYCS_MC" VARCHAR(100) NOT NULL,
"XYCS_LX" VARCHAR(20) NOT NULL,
"XYCS_MS" VARCHAR(256),
"XYCS_SFBY" INT DEFAULT 0,
CONSTRAINT "GXYYZC_MLJK_XYCS_PK" NOT CLUSTER PRIMARY KEY("XYCS_ID")) STORAGE(ON "CSP_MANAGER", CLUSTERBTR) AUTO_INCREMENT = 1749715486114889730;

COMMENT ON TABLE "CSP_MANAGER"."GXYYZC_NLJK_XYCS" IS '接口响应参数';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK_XYCS"."NLJK_ID" IS '能力接口ID';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK_XYCS"."XYCS_ID" IS '响应参数ID';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK_XYCS"."XYCS_LX" IS '响应参数类型';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK_XYCS"."XYCS_MC" IS '响应参数名称';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK_XYCS"."XYCS_MS" IS '描述';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK_XYCS"."XYCS_SFBY" IS '参数是否必要(默认0否 1是)';


