CREATE SCHEMA "CSP_MANAGER" AUTHORIZATION "CSP_MANAGER";

CREATE TABLE "CSP_MANAGER"."GXYYZC_NLJK"
(
"NLJK_ID" BIGINT AUTO_INCREMENT NOT NULL,
"NL_ID" BIGINT NOT NULL,
"NLJK_MC" VARCHAR(512) NOT NULL,
"NLJK_MS" VARCHAR(2048),
"DYLXZ" INT,
"BFSXZ" INT,
"NLJK_XYGS" TEXT,
"NLJK_XY" VARCHAR(20),
"NLJK_ZJDZ" VARCHAR(255),
"NLJK_URL" VARCHAR(255) NOT NULL,
"NLJK_BBH" VARCHAR(50),
"IS_DELETE" TINYINT DEFAULT 0,
"NLJK_CJSJ" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
"NLJK_GXSJ" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
"WG_GY" VARCHAR(255),
"WG_SY" VARCHAR(255),
"NLJK_QQFF" VARCHAR(50),
"NLJK_QQSL" TEXT,
"NLJK_XYSL" TEXT,
"NLJK_XYZTM" TEXT,
NOT CLUSTER PRIMARY KEY("NLJK_ID"),
CONSTRAINT "MANAGE_ABILITY_API_MANAGE_ABILITY_FK" FOREIGN KEY("NL_ID") REFERENCES "CSP_MANAGER"."GXYYZC_NL"("NL_ID"),
CONSTRAINT "GXYYZC_NLJK_URL_UN" UNIQUE("NLJK_URL")) STORAGE(ON "CSP_MANAGER", CLUSTERBTR) AUTO_INCREMENT = 1749715486085529603;

COMMENT ON TABLE "CSP_MANAGER"."GXYYZC_NLJK" IS '能力接口表';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."BFSXZ" IS '并发数限制';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."DYLXZ" IS '调用量限制';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."IS_DELETE" IS '逻辑删除';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."NLJK_BBH" IS '版本号';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."NLJK_CJSJ" IS '创建时间';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."NLJK_GXSJ" IS '更新时间';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."NLJK_ID" IS 'ApiID';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."NLJK_MC" IS 'api名称';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."NLJK_MS" IS 'api描述';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."NLJK_QQFF" IS '请求方式';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."NLJK_QQSL" IS '请求示例';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."NLJK_URL" IS 'URL路径';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."NLJK_XY" IS '协议http/https';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."NLJK_XYGS" IS '响应格式';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."NLJK_XYSL" IS '响应示例';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."NLJK_XYZTM" IS '响应状态码';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."NLJK_ZJDZ" IS '主机地址';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."NL_ID" IS '能力ID';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."WG_GY" IS '公钥';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLJK"."WG_SY" IS '私钥';


