CREATE SCHEMA "CSP_MANAGER" AUTHORIZATION "CSP_MANAGER";

CREATE TABLE "CSP_MANAGER"."GXYYZC_NLSQ"
(
"NLSQ_ID" BIGINT AUTO_INCREMENT NOT NULL,
"NL_ID" BIGINT NOT NULL,
"YY_ID" BIGINT NOT NULL,
"YH_ID" BIGINT,
"NL_MC" VARCHAR(50) NOT NULL,
"NL_LX" VARCHAR(50),
"YY_MC" VARCHAR(50) NOT NULL,
"DYLXZ" INT,
"BFSXZ" INT,
"NLSQ_SQJKLB" VARCHAR(255),
"QY_MC" VARCHAR(50),
"ZF_BMMC" VARCHAR(50),
"ZT" TINYINT DEFAULT 0,
"NLSQ_SQSM" TEXT,
"BZ" TEXT,
"NLSQ_SPSJ" TIMESTAMP(6),
"IS_DELETE" TINYINT DEFAULT 0,
"NLSQ_CJSJ" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
"NLSQ_GXSJ" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
"NLSQ_SFTYXY" TINYINT DEFAULT 0 NOT NULL,
"WG_QQMWGZ" VARCHAR(20) DEFAULT 'none' NOT NULL,
"WG_XYMWGZ" VARCHAR(20) DEFAULT 'none' NOT NULL,
NOT CLUSTER PRIMARY KEY("NLSQ_ID")) STORAGE(ON "CSP_MANAGER", CLUSTERBTR) AUTO_INCREMENT = 1749635062376300546;

COMMENT ON TABLE "CSP_MANAGER"."GXYYZC_NLSQ" IS '应用申请表';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."BFSXZ" IS '并发数限制';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."BZ" IS '备注(驳回、停用的原因)';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."DYLXZ" IS '调用量限制';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."IS_DELETE" IS '逻辑删除';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."NLSQ_CJSJ" IS '创建时间（提交时间）';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."NLSQ_GXSJ" IS '更新时间';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."NLSQ_ID" IS '能力申请表ID';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."NLSQ_SFTYXY" IS '是否同意所有服务所需协议(默认0同意 1不同意)';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."NLSQ_SPSJ" IS '审批时间';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."NLSQ_SQJKLB" IS '申请接口id列表（id之间用逗号隔开）';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."NLSQ_SQSM" IS '申请说明';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."NL_ID" IS '能力ID';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."NL_LX" IS '能力类型';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."NL_MC" IS '能力名称';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."QY_MC" IS '企业名称';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."WG_QQMWGZ" IS '请求密文规则(默认:none不做处理 crypt加密文 sign加签名 sign_crypt加密加签)';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."WG_XYMWGZ" IS '响应密文规则(默认:none不做处理 crypt加密文 sign加签名 sign_crypt加密加签)';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."YH_ID" IS '用户账户ID';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."YY_ID" IS '应用ID';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."YY_MC" IS '应用名称';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."ZF_BMMC" IS '政府部门名称';
COMMENT ON COLUMN "CSP_MANAGER"."GXYYZC_NLSQ"."ZT" IS '状态(默认:0待审核 1审核通过 2审核不通过 3已停用)';


